### ISSUE TITLE
thank you! and potential PRs I can make?

### ISSUE THREAD

**Issue by acao** [EmaSuriano/gatsby-starter-event-calendar#207]
first off, *thank you*! this is a fantastic starter, and makes us look really good.

I've forked it to this repo:
https://github.com/cle-event-calendar/cle-event-calendar.github.io

with this result so far:
https://cle-event-calendar.netlify.app/

here's a few features i added in my fork, let me know which you'd like me to make PRs for, if any:

- scheduled github action that deploys to netlify every 30 minutes (adjustable) as well as on push
- "publish" checkbox column to decide whether events should be shown or not
- a static page per event (using row ID for the url, less than ideal)
- a color coded 'event type' field, which I may even make individual pages for as well, for a "filter" of event types

my favorite feature is the responsiveness, and how all the complexities of actually rendering a calendar with react are mostly abstracted away from presentational components. awesome work!

**Comment by EmaSuriano** [comment]
Hello @acao! Thanks for the kind words and amazing implementation 👏 Some comments regarding the features:

- I solved this by triggering an automatic build of netlify on every change in Google Spreadsheet. I used Zapier for that.
- Regarding the `publish` checkbox, this can actually can be solved by editing which answer go inside the spreadsheet or not. I think that knowing that every row that it's inside the spreadsheet exists in the calendar is better.
- One of the features I would love to see is this one: Static page per event. I think it's the perfect scenario for a nice Markdown Renderer too :)
- I like this idea but, how do you determine the color of the event? Also, it will add a new question inside the form

I would love to know how did you find the codebase and if it was easy for you to add the features :)
