### ISSUE TITLE
Google sheet directions need update

### ISSUE THREAD

**Issue by imyjimmy** [EmaSuriano/gatsby-starter-event-calendar#430]
Google's API interface has changed a bit, to the point where this tutorial is confusing. 

In particular this part

> You'll be redirected to a new page to create the service account key, just make sure the option of "App Engine default service account" is selected and the key type marked as JSON.

Needs updating, as I couldn't find any setting called App Engine default service account, this was the closest I could find:
<img width="822" alt="Screen Shot 2020-12-14 at 7 29 29 PM" src="https://user-images.githubusercontent.com/489440/102167286-fab71c00-3e42-11eb-939c-75695df5c798.png">

It didn't work though afaik

**Comment by EmaSuriano** [comment]
Hey @imyjimmy sorry for the huge delayed, I updated the project and start using a new plugin to fetch for the data, which has the instructions updated and way more detailed than here. It should be good to go now! 😄
